#!/usr/bin/env node
/**
 * Reads audit-report.json and prints Markdown for GitHub PR comments / step summary.
 * Usage: node scripts/pr-comment.js audit-report.json
 */
const fs = require('fs');
const path = require('path');

const file = process.argv[2] || 'audit-report.json';
if (!fs.existsSync(file)) {
  console.log('## SwaggerPilot API Audit\n\nNo report file found.');
  process.exit(0);
}

const report = JSON.parse(fs.readFileSync(file, 'utf8'));
const readiness = report.releaseReadiness || { status: 'warn', label: 'Review', reasons: [] };
const drift = report.contractDrift;
const emoji = readiness.status === 'go' ? '✅' : readiness.status === 'warn' ? '⚠️' : '❌';

let md = `## ${emoji} SwaggerPilot API Audit — ${report.title}\n\n`;
md += `| Metric | Value |\n|--------|-------|\n`;
md += `| Pass rate | **${report.passRate}%** |\n`;
md += `| Tests run | ${report.totalTests} |\n`;
md += `| Passed / Failed / Errors | ${report.passed} / ${report.failed} / ${report.errors} |\n`;
md += `| Release readiness | **${readiness.label}** |\n`;
if (report.estimatedManualHoursSaved) {
  md += `| Est. manual QA saved | ~${report.estimatedManualHoursSaved}h |\n`;
}
md += `\n`;

if (readiness.reasons?.length) {
  md += `### Release gate\n`;
  readiness.reasons.forEach((r) => { md += `- ${r}\n`; });
  md += `\n`;
}

if (drift?.items?.length) {
  md += `### OpenAPI contract drift (${drift.items.length} issue(s), score ${drift.driftScore}/100)\n`;
  drift.items.slice(0, 5).forEach((item) => {
    md += `- **${item.severity.toUpperCase()}** \`${item.method} ${item.path}\`: ${item.message}\n`;
  });
  md += `\n`;
}

if (report.topFailureInsights?.length) {
  md += `### Top failures (rule-based diagnostics)\n`;
  report.topFailureInsights.slice(0, 5).forEach((item) => {
    const d = item.diagnostic;
    md += `- \`${item.testKey.split('-').slice(0, 2).join(' ')}\` — ${d.likelyCause} (*${d.ownerHint}*)\n`;
  });
  md += `\n`;
}

md += `_Full report artifact attached. Generated by SwaggerPilot._\n`;
console.log(md);
