import { Injectable, Logger } from '@nestjs/common';
import axios from 'axios';
import { ParsedEndpoint } from '../swagger-parser/swagger-parser.dto';
import { GeneratedTest } from './rule-engine.service';

@Injectable()
export class GeminiService {
  private readonly logger = new Logger(GeminiService.name);
  private readonly apiKey = process.env.GEMINI_API_KEY?.trim();

  /** Returns true if a Gemini API key is present in the environment. */
  isConfigured(): boolean {
    return !!this.apiKey;
  }
  private readonly apiUrl =
    'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent';


  /**
   * POST to Gemini with automatic retry on 429 (rate-limit).
   * Waits 2s on first retry, 5s on second, then gives up.
   */
  /**
   * POST to Gemini with automatic retry on 429 (rate-limit).
   * Waits 2s on first retry, 5s on second, then throws.
   *
   * @param prompt    - The full prompt text to send
   * @param maxTokens - Maximum output tokens (default 2048)
   * @returns Raw text from the first candidate response
   */
  private async geminiPost(prompt: string, maxTokens = 2048): Promise<string> {
    const delays = [2000, 5000];
    for (let attempt = 0; attempt <= delays.length; attempt++) {
      try {
        const response = await axios.post(
          `${this.apiUrl}?key=${this.apiKey}`,
          {
            contents: [{ parts: [{ text: prompt }] }],
            generationConfig: { temperature: 0.5, maxOutputTokens: maxTokens },
          },
          { timeout: 30000 },
        );
        return response.data?.candidates?.[0]?.content?.parts?.[0]?.text ?? '';
      } catch (err: any) {
        const status = err?.response?.status;
        if (status === 429 && attempt < delays.length) {
          this.logger.warn(`Gemini rate-limited (429) — retrying in ${delays[attempt] / 1000}s...`);
          await new Promise((r) => setTimeout(r, delays[attempt]));
        } else {
          throw err;
        }
      }
    }
    throw new Error('Gemini rate-limit: all retries exhausted');
  }

  /**
   * Asks Gemini to generate up to 5 creative edge-case tests for a single
   * endpoint that are NOT already covered by the rule engine.
   *
   * Falls back to an empty array on any error so the main run is never blocked.
   *
   * @param endpoint      - The parsed endpoint to generate edge cases for
   * @param existingTests - Tests already generated by the rule engine (used in the prompt to avoid duplicates)
   * @returns Array of up to 5 AI-generated test cases
   */
  async generateEdgeCases(
    endpoint: ParsedEndpoint,
    existingTests: GeneratedTest[],
  ): Promise<GeneratedTest[]> {
    if (!this.apiKey) {
      this.logger.warn('GEMINI_API_KEY not set — skipping AI test generation');
      return [];
    }

    const prompt = this.buildPrompt(endpoint, existingTests);

    try {
      const response = await axios.post(
        `${this.apiUrl}?key=${this.apiKey}`,
        {
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: {
            temperature: 0.7,
            maxOutputTokens: 2048,
          },
        },
        { timeout: 30000 },
      );

      const rawText =
        response.data?.candidates?.[0]?.content?.parts?.[0]?.text || '';

      return this.parseGeminiResponse(rawText, endpoint);
    } catch (err) {
      this.logger.warn(`Gemini API failed: ${err.message} — continuing without AI tests`);
      return [];
    }
  }

  private buildPrompt(endpoint: ParsedEndpoint, existingTests: GeneratedTest[]): string {
    const schema = endpoint.requestBody?.schema;
    const existingNames = existingTests.map((t) => t.testName).join('\n');

    return `You are an API test engineer. Generate 5 creative edge case tests for this API endpoint that are NOT already covered by the existing tests.

Endpoint: ${endpoint.method} ${endpoint.path}
Summary: ${endpoint.summary || 'No description'}
Request body schema: ${JSON.stringify(schema || {}, null, 2)}
Response codes in spec: ${Object.keys(endpoint.responses).join(', ')}

Already covered tests:
${existingNames}

Return ONLY a valid JSON array (no markdown, no backticks, no explanation) with this exact structure:
[
  {
    "testName": "descriptive test name",
    "method": "${endpoint.method}",
    "path": "${endpoint.path.replace(/\{[^}]+\}/g, '1')}",
    "headers": {"Content-Type": "application/json"},
    "queryParams": {},
    "body": {},
    "expectedStatus": [400],
    "category": "ai-edge-case",
    "description": "why this test matters"
  }
]

Ideas to consider: SQL injection, XSS in string fields, very large payloads, Unicode/emoji, duplicate entries, concurrent requests simulation, extremely long strings, null values for non-nullable fields, negative numbers for unsigned fields, zero values.`;
  }

  private parseGeminiResponse(rawText: string, endpoint: ParsedEndpoint): GeneratedTest[] {
    try {
      // Strip markdown code blocks if present
      let cleaned = rawText.trim();
      cleaned = cleaned.replace(/^```json\s*/i, '').replace(/\s*```$/, '');
      cleaned = cleaned.replace(/^```\s*/, '').replace(/\s*```$/, '');

      // Find JSON array
      const start = cleaned.indexOf('[');
      const end = cleaned.lastIndexOf(']');
      if (start === -1 || end === -1) {
        this.logger.warn('Gemini response did not contain valid JSON array');
        return [];
      }

      const jsonStr = cleaned.substring(start, end + 1);
      const parsed = JSON.parse(jsonStr);

      if (!Array.isArray(parsed)) return [];

      // Validate and sanitize each test
      return parsed
        .filter((t) => t.testName && t.method && t.path)
        .map((t) => ({
          testName: `[AI] ${t.testName}`,
          method: t.method || endpoint.method,
          path: t.path || endpoint.path,
          headers: t.headers || {},
          queryParams: t.queryParams || {},
          body: t.body !== undefined ? t.body : null,
          expectedStatus: Array.isArray(t.expectedStatus)
            ? t.expectedStatus
            : [t.expectedStatus || 400],
          category: 'ai-edge-case',
          description: t.description || 'AI-generated edge case',
        }))
        .slice(0, 5); // Max 5 AI tests per endpoint
    } catch (err) {
      this.logger.warn(`Failed to parse Gemini response: ${err.message}`);
      return [];
    }
  }

  /**
   * Sends the complete run report summary to Gemini and returns an
   * AI-written executive analysis in Markdown format.
   *
   * Includes retry logic for 429 rate-limit errors.
   * Returns a user-friendly error message string on failure (never throws).
   *
   * @param report - The fully assembled TestReport to analyse
   * @returns Markdown string with executive summary, failure patterns, and recommendations
   */
  async analyzeReport(report: any): Promise<string> {
    if (!this.apiKey) {
      return '### ⚠️ Gemini API Key Not Set\nAI analysis could not be run because the `GEMINI_API_KEY` environment variable is missing on the server.';
    }

    const failedTestsSummary = (report.failedTests || [])
      .slice(0, 15) // limit to top 15 failures to avoid token limits
      .map(
        (t: any) =>
          `- **${t.method} ${t.path}** (${t.testName}): Expected ${t.expected.join(' or ')}, got ${t.actual}. Error: ${t.errorMessage || 'None'}`
      )
      .join('\n');

    const prompt = `You are a Principal QA Intelligence Engineer and Site Reliability Engineer. 
Analyze this API test suite report:

API Title: ${report.title}
Base URL: ${report.baseUrl}
Total Tests Executed: ${report.totalTests}
Passed: ${report.passed} (${report.passRate}% pass rate)
Failed: ${report.failed}
Errors: ${report.errors}
Skipped: ${report.skipped}

Failed Tests (Top 15):
${failedTestsSummary || 'No failures! All tests passed successfully.'}

Provide a high-density, professional QA Executive Summary in Markdown. Do not include markdown code ticks wrapper for the entire response. Structure the response with these sections:
1. **Executive Summary**: General health overview of the API under test.
2. **Failure Pattern Analysis**: Group common issues (e.g. auth issues, schema mismatches, server crashes) and explain why they occurred.
3. **Actionable Recommendations**: Clear, prioritized recommendations for developers to stabilize the API.`;

    try {
      const text = await this.geminiPost(prompt, 2048);
      return text || 'No response from AI.';
    } catch (err: any) {
      const status = err?.response?.status;
      if (status === 429) {
        this.logger.warn('Gemini rate-limited on report analysis — returning friendly message');
        return '### ⚠️ Rate Limited\nGemini API quota reached. Wait 60 seconds and click **Request AI Insights** again.';
      }
      this.logger.error(`AI Report Analysis failed: ${err.message}`);
      return `### ⚠️ AI Analysis Failed\nAn error occurred while generating insights: ${err.message}`;
    }
  }

  /**
   * Asks Gemini to classify a single failing test into a structured
   * {@link FailureDiagnostic} with root cause, owner hint, and fix suggestion.
   *
   * Falls back to a rule-based generic diagnosis on error.
   *
   * @param test - The failing TestResult to diagnose
   * @returns Structured diagnostic object
   */
  async analyzeFailureStructured(test: any): Promise<{
    likelyCause: string;
    ownerHint: 'backend' | 'openapi-spec' | 'auth' | 'infrastructure';
    suggestedFix: string;
    severity: 'critical' | 'high' | 'medium' | 'low';
  } | null> {
    if (!this.apiKey) return null;

    const prompt = `Analyze this FAILED API test. Use ONLY facts from the data below — do not invent endpoints or status codes.

Test: ${test.testName}
Category: ${test.category}
${test.method} ${test.path}
Expected HTTP: ${Array.isArray(test.expected) ? test.expected.join(' or ') : test.expected}
Actual HTTP: ${test.actual ?? 'none'}
Error: ${test.errorMessage || 'none'}
Request body: ${JSON.stringify(test.requestBody ?? null)}
Response body (truncated): ${JSON.stringify(test.responseBody ?? null).slice(0, 800)}

Return ONLY valid JSON (no markdown):
{
  "likelyCause": "one sentence factual root cause",
  "ownerHint": "backend|openapi-spec|auth|infrastructure",
  "suggestedFix": "one concrete fix step",
  "severity": "critical|high|medium|low"
}`;

    try {
      const response = await axios.post(
        `${this.apiUrl}?key=${this.apiKey}`,
        {
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: { temperature: 0.2, maxOutputTokens: 512 },
        },
        { timeout: 20000 },
      );

      const raw = response.data?.candidates?.[0]?.content?.parts?.[0]?.text || '';
      const start = raw.indexOf('{');
      const end = raw.lastIndexOf('}');
      if (start === -1 || end === -1) return null;

      const parsed = JSON.parse(raw.slice(start, end + 1));
      const owners = ['backend', 'openapi-spec', 'auth', 'infrastructure'];
      const severities = ['critical', 'high', 'medium', 'low'];
      if (!parsed.likelyCause || !parsed.suggestedFix) return null;

      return {
        likelyCause: String(parsed.likelyCause).slice(0, 500),
        ownerHint: owners.includes(parsed.ownerHint) ? parsed.ownerHint : 'backend',
        suggestedFix: String(parsed.suggestedFix).slice(0, 500),
        severity: severities.includes(parsed.severity) ? parsed.severity : 'high',
      };
    } catch (err) {
      this.logger.warn(`Structured AI diagnostic failed: ${err.message}`);
      return null;
    }
  }

  async analyzeFailure(test: any): Promise<string> {
    const structured = await this.analyzeFailureStructured(test);
    if (structured) {
      return `### Root Cause Analysis\n${structured.likelyCause}\n\n**Owner:** ${structured.ownerHint} | **Severity:** ${structured.severity}\n\n### Recommended Fix\n${structured.suggestedFix}`;
    }
    if (!this.apiKey) {
      return '### Gemini API Key Not Set\nConfigure `GEMINI_API_KEY` on the server for AI diagnostics, or use rule-based analysis.';
    }
    return '### AI Analysis Unavailable\nCould not produce structured diagnostics. Rule-based analysis is shown in the UI.';
  }
}

