import { jsPDF } from 'jspdf';
import { TestReport } from '../types';
import { CATEGORY_LABELS } from '../types';
import { estimateHoursSaved } from './reportHistory';

export function exportClientPdf(report: TestReport): void {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const margin = 14;
  let y = margin;
  const pageWidth = pdf.internal.pageSize.getWidth();
  const contentWidth = pageWidth - margin * 2;

  const line = (text: string, size = 10, bold = false, color: [number, number, number] = [30, 41, 59]) => {
    pdf.setFontSize(size);
    pdf.setFont('helvetica', bold ? 'bold' : 'normal');
    pdf.setTextColor(color[0], color[1], color[2]);
    const lines = pdf.splitTextToSize(text, contentWidth);
    for (const ln of lines) {
      if (y > 275) {
        pdf.addPage();
        y = margin;
      }
      pdf.text(ln, margin, y);
      y += size * 0.45;
    }
    y += 2;
  };

  const nonSkipped = report.passed + report.failed + report.errors;
  const healthScore = nonSkipped > 0 ? Math.round((report.passed / nonSkipped) * 100) : 100;
  const hoursSaved = estimateHoursSaved(report.totalTests);

  pdf.setFillColor(37, 99, 235);
  pdf.rect(0, 0, pageWidth, 28, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('SwaggerPilot — API Audit Report', margin, 12);
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Client-ready executive summary', margin, 20);

  y = 38;
  pdf.setTextColor(15, 23, 42);

  line(report.title, 14, true);
  line(`Base URL: ${report.baseUrl}`, 9);
  line(`Completed: ${new Date(report.completedAt).toLocaleString()}`, 9);
  line(`Duration: ${(report.durationMs / 1000).toFixed(1)} seconds`, 9);

  y += 4;
  line('Executive summary', 12, true, [37, 99, 235]);

  line(`API Health Score: ${healthScore}% (${healthScore >= 85 ? 'B+' : healthScore >= 70 ? 'C' : 'Needs attention'})`, 11, true);
  line(`Tests executed: ${report.totalTests}  |  Passed: ${report.passed}  |  Failed: ${report.failed}  |  Errors: ${report.errors}  |  Skipped: ${report.skipped}`, 10);
  line(`Pass rate: ${report.passRate}%`, 10);
  line(`Estimated manual QA effort replaced: ~${hoursSaved} hours (${report.totalTests} tests × ~2 min each)`, 10);

  if (report.tokenExpiryWarning) {
    line('⚠ Warning: Possible auth token expiry detected during the run.', 9, false, [180, 83, 9]);
  }

  y += 2;
  line('Top failures', 12, true, [220, 38, 38]);

  const topFails = report.failedTests.slice(0, 8);
  if (topFails.length === 0) {
    line('No failures — all executed tests passed.', 10, false, [22, 163, 74]);
  } else {
    topFails.forEach((t, i) => {
      line(
        `${i + 1}. [${t.status}] ${t.method} ${t.path} — expected ${t.expected.join('/')}, got ${t.actual ?? 'N/A'}`,
        9,
      );
      if (t.errorMessage) {
        line(`   ${t.errorMessage}`, 8, false, [100, 116, 139]);
      }
    });
  }

  y += 2;
  line('Results by category', 12, true, [37, 99, 235]);
  report.byCategory.slice(0, 10).forEach((c) => {
    const label = CATEGORY_LABELS[c.category] || c.category;
    const rate = c.total > 0 ? Math.round((c.passed / c.total) * 100) : 0;
    line(`• ${label.replace(/^[^\s]+\s/, '')}: ${c.passed}/${c.total} passed (${rate}%)`, 9);
  });

  y += 4;
  line('Generated by SwaggerPilot — automated OpenAPI audit', 8, false, [100, 116, 139]);
  line('Full technical report available in JSON, Excel, CSV, and Postman collection exports.', 8, false, [100, 116, 139]);

  const timestamp = new Date().toISOString().slice(0, 19).replace(/[:T]/g, '-');
  pdf.save(`swagger-pilot-client-report-${timestamp}.pdf`);
}
