import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { TestReport } from '../types';
function buildClientReadme(report: TestReport): string {
  const readiness = report.releaseReadiness;
  const drift = report.contractDrift;
  return `# API Audit — ${report.title}

**Date:** ${new Date(report.completedAt).toLocaleString()}  
**Base URL:** ${report.baseUrl}  
**Health score:** ${report.passRate}% pass rate  
**Release readiness:** ${readiness?.label ?? 'N/A'}

## Summary
- Tests executed: ${report.totalTests}
- Passed: ${report.passed} | Failed: ${report.failed} | Errors: ${report.errors}
- Estimated manual effort replaced: ~${report.estimatedManualHoursSaved ?? '—'} hours

## OpenAPI contract drift
${drift?.items?.length ? drift.items.slice(0, 8).map((i) => `- [${i.severity}] ${i.method} ${i.path}: ${i.message}`).join('\n') : 'No drift detected.'}

## Top issues
${(report.topFailureInsights ?? []).slice(0, 8).map((item, n) => `${n + 1}. ${item.diagnostic.likelyCause} (${item.diagnostic.ownerHint})`).join('\n') || 'No failures.'}

## Package contents
- \`audit-report.json\` — full machine-readable results
- \`failures.postman_collection.json\` — replay failed cases in Postman
- \`README-for-client.md\` — this file

_Generated by SwaggerPilot automated OpenAPI audit._
`;
}

export async function exportClientPack(report: TestReport): Promise<void> {
  const zip = new JSZip();

  zip.file('audit-report.json', JSON.stringify(report, null, 2));
  zip.file('README-for-client.md', buildClientReadme(report));

  const postman = buildPostmanJson(report);
  zip.file('failures.postman_collection.json', JSON.stringify(postman, null, 2));

  const summary = {
    title: report.title,
    completedAt: report.completedAt,
    passRate: report.passRate,
    releaseReadiness: report.releaseReadiness,
    contractDriftScore: report.contractDrift?.driftScore,
    topFailures: (report.topFailureInsights ?? []).slice(0, 10),
  };
  zip.file('executive-summary.json', JSON.stringify(summary, null, 2));

  const blob = await zip.generateAsync({ type: 'blob' });
  const timestamp = new Date().toISOString().slice(0, 19).replace(/[:T]/g, '-');
  saveAs(blob, `api-audit-pack-${timestamp}.zip`);
}

function buildPostmanJson(report: TestReport) {
  const failures = report.failedTests.length > 0
    ? report.failedTests
    : report.allTests.filter((t) => t.status === 'FAIL' || t.status === 'ERROR');

  return {
    info: {
      name: `${report.title} — Failed Tests`,
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
    },
    variable: [
      { key: 'baseUrl', value: report.baseUrl },
      { key: 'authToken', value: 'YOUR_TOKEN_HERE' },
    ],
    item: failures.map((t) => ({
      name: `[${t.status}] ${t.method} ${t.path}`,
      request: {
        method: t.method,
        header: [{ key: 'Accept', value: '*/*' }],
        url: t.fullUrl,
      },
    })),
  };
}
